CREATE TABLE Events (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    AggregateId UNIQUEIDENTIFIER NOT NULL,
    Assembly NVARCHAR(MAX) NOT NULL,
	Type NVARCHAR(MAX) NOT NULL,
	Event NVARCHAR(MAX) NOT NULL,
    Data NVARCHAR(MAX) NOT NULL,
    Timestamp DATETIME NOT NULL
);