CREATE TABLE EventStore (
    AggregateId UNIQUEIDENTIFIER NOT NULL,
    EventId UNIQUEIDENTIFIER NOT NULL,
    EventData NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_EventStore PRIMARY KEY (AggregateId, EventId)
);