CREATE TABLE Event (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    AggregateId UNIQUEIDENTIFIER NOT NULL,    
	Class NVARCHAR(MAX) NOT NULL,
	Dll NVARCHAR(MAX) NOT NULL,
	Event NVARCHAR(MAX) NOT NULL,
    Data NVARCHAR(MAX) NOT NULL,
    Timestamp DATETIME NOT NULL
);